### ISSUE TITLE
Exposing "Common Operations" to shinyAce functions

### ISSUE THREAD

**Issue by petermeissner** [trestletech/shinyAce#44]
I was wondering if it would be possible to expose Ace operations other than those covered by `updateAceEditor` already? 

Namely I think things like the following would be very useful for general UI building and text editing with shinyAce ([Link](https://ace.c9.io/#nav=howto)):
- get selected text (`editor.session.getTextRange(editor.getSelectionRange());`)
- get the current cursor line and column (`editor.selection.getCursor();`)
- go to a line (`editor.gotoLine(lineNumber);`)

**Comment by mslegrand** [comment]
> I was wondering if it would be possible to expose Ace operations other
> than those covered by `updateAceEditor` already?
>
> Namely I think things like the following would be very useful for general
> UI building and text editing with shinyAce
> ([Link](https://ace.c9.io/#nav=howto)):
>
> - get selected text
> (`editor.session.getTextRange(editor.getSelectionRange());`)
> - get the current cursor line and column (`editor.selection.getCursor();`)
> - go to a line (`editor.gotoLine(lineNumber);`)
>
>
>
>
>
>
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/trestletech/shinyAce/issues/44


The answer should be yes. I am actually quite interested in doing this.
The extension to api should be thin, with minimal interviewing javascript
so that the api could be fully exposed. However the devil is in the
details.

Essentially, we want to enhance browser to server and server to browser
messaging.

Currently:
1. Server to Browser is handle by updateAceEditor. (easy to enhance)
2. Browser to Server is handle by observers provide upon initialization of
aceEditor

In the ACE api, we have
1. listeners (essentially observers)
2. pure setter functions (sets a value)
3. pure getter functions (returns a value)
4. functions which both set and get ( both a sets value and returns a value)

Update Ace Editor can easily be expanding to include 2: pure setters.  But
3 and 4 require using shiny observers to retrieve the values.

One approach would be to create a shinyAce  function similar to

setgetshinyACE(session, editorId, aceApiCmdName, shinyObserver, params)

Then usage might look like be:

getTextRange(session, range){
    input$myReturnString ="" # assume "" is not valid
    setgetshinyACE(session, "myAceEditorId", "getTextRange",  
"myReturnString",  range)
}

observer({
  if(input$myReturnString!=""){ #assuming that "" is never a valid
    ... #do something
  }
})


An observer updates whenever a value changes, so to force the reactive
handling of the return, we first set it to some impossible value, do the
call, then let reactivity do the right response.


Some obvious use cases we would like to be able to handle are:

1. highlight a line that contains a runtime error.
2. Add a breakpoint
3. Add bookmarks so we can jump through the code
4. Execute the current line (the line containing the cursor) and move to
the next line.

Any thoughts?

**Comment by petermeissner** [comment]
I do not know about the implementation side - I guess this was directed to the other package developers anyways - but on top of your use case I can throw in my own one as well:

I would like to do content coding in R and shinyAce would be awesome for building the GUI on top of the backend - because, looks good, is powerful, and is integrated in Shiny. So my use case would be to mark some text, klick a button and pass the character range to the backend to process the information.

**Comment by vnijs** [comment]
See https://github.com/trestletech/shinyAce/blob/master/R/ace-editor.R#L173-L250 for new relevant code. If you have ideas for a pull request to improve on this implementation (e.g., using https://ace.c9.io/api/editor.html#Editor.jumpToMatching).

**Comment by vnijs** [comment]
A number of things you requested are described in the examples. See the updated README.md file for details. 

https://vnijs.shinyapps.io/shinyAce-05-hotkeys/
https://vnijs.shinyapps.io/shinyAce-09-selectionId/

**Comment by vnijs** [comment]
See https://github.com/trestletech/shinyAce/issues/63 for an example of how to "jump" through and evaluate R (or Rmarkdown) code using keyboard shortcuts.
